FLUT-927176 - [Others] Added tutorial samples in user guide
syncfusion-content/flutter-docs pull request #1078
Opened 2024-12-17 04:44 UTC by sfHariHaraSudhan

## Description ##

Updated the published video tutorial samples in user guide on the below pages.

**SfCartesianChart** - How to Create Flutter Charts from JSON Data [[Getting started with Flutter Cartesian Charts widget | Syncfusion](https://help.syncfusion.com/flutter/cartesian-charts/getting-started#bind-data-source)]
![image](https://github.com/user-attachments/assets/9c6d6972-794c-4d58-b0c0-6335cebad552)

**SfCalendar** - How to Display More Appointments in the Flutter Calendar [For this, I thought, we can add in [appointments page.](https://help.syncfusion.com/flutter/calendar/appointments)]
![image](https://github.com/user-attachments/assets/352b968a-89b7-4b28-aad2-7854308e6f68)

**SfCalendar**  - How to Customize the Date Picker's Appearance in the Flutter Calendar [[Date Navigations in Flutter Event Calendar widget | Syncfusion](https://help.syncfusion.com/flutter/calendar/date-navigations#show-date-picker)] 
![image](https://github.com/user-attachments/assets/5f06df14-8e55-4516-9749-3cbd81d49f41)

2024-12-19 04:00 UTC, LavanyaGowtham2021 requested changes

2024-12-19 06:06 UTC, sfHariHaraSudhan commented on Flutter/calendar/date-navigations.md
> +To know more about how to customize the Date Picker's ppearance in the Flutter Calendar, you can check on this video.
Hi,
Resolved this spelling mistakes.
Regards,
Hari Hara Sudhan. K.

2024-12-19 06:07 UTC, sfHariHaraSudhan commented on Flutter/calendar/appointments.md
> +<style>#flutterChartVideoTutorial{width : 90% !important; height: 300px !important }</style>
Hi,
Missed to update it properly at first. Modified now properly.
Regards,
Hari Hara Sudhan. K.

2024-12-19 06:07 UTC, sfHariHaraSudhan commented on Flutter/calendar/appointments.md
> +To know more about how to display more appointments in the Flutter Calendar, you can check on this video.
Hi,
Modified the content as mentioned.
Regards,
Hari Hara Sudhan. K.

2024-12-19 06:07 UTC, sfHariHaraSudhan commented on Flutter/calendar/date-navigations.md
> +<style>#flutterChartVideoTutorial{width : 90% !important; height: 300px !important }</style>
Hi,
Missed to update it properly at first. Modified now properly.
Regards,
Hari Hara Sudhan. K.

2024-12-19 06:10 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [FLUT-927176-tutorial-samples-integration](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/console)**

2024-12-19 06:14 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-927176-tutorial-samples-integration](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/console)**

2024-12-19 06:16 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/)<br/>Build Location: [FLUT-927176-tutorial-samples-integration](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/385/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-20 04:05 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [FLUT-927176-tutorial-samples-integration](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/console)**

2024-12-20 04:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-927176-tutorial-samples-integration](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/console)**

2024-12-20 04:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-927176-tutorial-samples-integration](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/386/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-20 04:24 UTC, LavanyaGowtham2021 approved these changes
Fine

2024-12-20 04:24 UTC, merged