FLUT-6235 - [Feature] UG document for DataGrid
syncfusion-content/flutter-docs pull request #202
Opened 2022-03-17 11:59 UTC by Tamilarasan-Paranthaman

## Description ##

I have prepared content for the custom sort icon feature and current cell is in editing enhancement for volume 1 2022 release.

2022-03-17 12:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/console)**

2022-03-17 12:01 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/)<br/>Build Location: [FLUT-6235-datagrid-cell-style](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/399/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-17 12:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/console)**

2022-03-17 12:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6235-datagrid-cell-style](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/402/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-21 09:32 UTC, NeelakandanKannan requested changes
Hi @Tamilarasan-Paranthaman ,

I have added my comments.

2022-03-21 09:32 UTC, NeelakandanKannan commented on Flutter/datagrid/editing.md
> +You can check whether current cell is in editing or not from the `SfDataGrid.isCurrentCellInEditing`. If current cell is in edit mode it will return true else return false.
You can check whether current cell is in editing or not by using  `DataGridController.isCurrentCellInEditing` property.

2022-03-21 09:32 UTC, NeelakandanKannan commented on Flutter/datagrid/sorting.md
> +`SfDataGrid` allows to change the sort icon through [SfDataGridTheme.SfDataGridThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData-class.html) property.
`SfDataGrid` allows to change the sort icon through using `SfDataGridThemeData.sortIcon` property. The DataGrid should be wrapped inside the `SfDataGridTheme`.  The given icon will be shown with the size (16*16).

2022-03-21 09:32 UTC, NeelakandanKannan commented on Flutter/datagrid/sorting.md
> +The sort icon can be changed by using [SfDataGridThemeData.sortIcon]. The following code describes how to change sort icon color by using [SfDataGridTheme]
This line is not required.

2022-03-21 11:08 UTC, Tamilarasan-Paranthaman commented
rebuild

2022-03-22 05:55 UTC, laksmipriyamurugesan commented on Flutter/datagrid/editing.md
> +## How to check whether current cell is in editing mode
How to check whether the current cell is in editing mode

2022-03-22 05:55 UTC, laksmipriyamurugesan commented on Flutter/datagrid/editing.md
> +You can check whether current cell is in editing or not by using `DataGridController.isCurrentCellInEditing` property.
You can check whether the current cell is in editing or not by using the `DataGridController.isCurrentCellInEditing` property.

2022-03-22 05:59 UTC, laksmipriyamurugesan commented on Flutter/datagrid/sorting.md
> +## Set custom sorting icon
Set a custom sorting icon

2022-03-22 06:23 UTC, laksmipriyamurugesan commented on Flutter/datagrid/sorting.md
> +`SfDataGrid` allows to change the sort icon through using `SfDataGridThemeData.sortIcon` property. The DataGrid should be wrapped inside the `SfDataGridTheme`.
`SfDataGrid` allows you to change the sort icon by using the `SfDataGridThemeData.sortIcon` property.

2022-03-22 06:25 UTC, laksmipriyamurugesan commented on Flutter/datagrid/sorting.md
> +The `SfDataGridThemeData` and `SfDataGridTheme` classes are available in [syncfusion_flutter_core](https://pub.dev/packages/syncfusion_flutter_core) package. So, import the below file,
So, import the following file.

2022-03-22 06:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/console)**

2022-03-22 06:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6235-datagrid-cell-style](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/414/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-03-22 07:55 UTC, NeelakandanKannan approved these changes
The changes are fine.

2022-03-22 07:55 UTC, merged