FLUT-6424 - [Others] Added the UG for integrate SfSignature Pad with SfPdfViewer.
syncfusion-content/flutter-docs pull request #244
Opened 2022-04-12 10:32 UTC by deepika134

## Description ##

 Added the UG for integrate the SignaturePad signatures to Syncfusion Flutter PdfViewer.

2022-04-12 10:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/console)**

2022-04-12 10:34 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/)<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/485/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-12 11:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/console)**

2022-04-12 11:21 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/)<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/486/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-12 12:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/console)**

2022-04-12 12:18 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/)<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/487/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 05:14 UTC, deepika134 commented
rebuild

2022-04-22 05:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/console)**

2022-04-22 05:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/495/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 09:07 UTC, dillibabu1802 commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +# How to add SfSignaturePad signature in SfPdfViewer?
Title  - Add digital signature in SfPdfViewer using SfSignaturePad

2022-04-22 09:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/console)**

2022-04-22 09:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/496/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 09:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/console)**

2022-04-22 09:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/497/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 10:15 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +In the `_handleSigningProcess()` method, initially convert the signature drawn in the SfSignaturePad as an image using the [toImage()](https://pub.dev/documentation/syncfusion_flutter_signaturepad/la
In the `_handleSigningProcess()` method, initially convert the signature drawn in the SfSignaturePad as an image using the [toImage()](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePadState/toImage.html) method in SfSignaturePad .Then create a [PdfSignatureField()](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfSignatureField-class.html) and drew the signature image in the PDF document using the [drawImage()](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfGraphics/drawImage.html) method in `Syncfusion PDF Library` and then saved the document as bytes and then loaded those bytes using the [SfPdfViewer.memory()](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.memory.html). The following code example explains the same.

2022-04-22 10:20 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +    //Gets the first page of the document
//Get the first page of the document

2022-04-22 10:21 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +    //Creates a digital signature and sets signature information.
//Create a digital signature and set the signature information.

2022-04-22 10:21 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +            //Creates a certificate instance from the PFX file with a private key.
//Create a certificate instance from the PFX file with a private key.

2022-04-22 10:21 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +    //Gets the signature field appearance graphics.
//Get the signature field appearance graphics.

2022-04-22 10:21 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +    //Draws the signature image in PDF page.
//Draw the signature image in the PDF page.

2022-04-22 10:22 UTC, carolinedolly commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +    //Flattens the PDF form field annotation
//Flatten the PDF form field annotation

2022-04-22 10:25 UTC, carolinedolly approved these changes

2022-04-22 10:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/console)**

2022-04-22 10:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/498/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 11:50 UTC, dillibabu1802 requested changes

2022-04-22 12:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/499/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 12:41 UTC, dillibabu1802 commented on Flutter/pdf-viewer/How to/Add SignaturePad signatures to Syncfusion Flutter PdfViewer.md
> +In the `_handleSigningProcess()` method, save the signature as image in SfSignaturePad using the [toImage()](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignat
In the `_handleSigningProcess()` method, the signature in SfSignaturePad is saved as image using the [toImage()](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePadState/toImage.html) method. Create a [PdfSignatureField()](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfSignatureField-class.html) and add the signature image as digital signature in the PDF document using the [drawImage()](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfGraphics/drawImage.html) method in `Syncfusion PDF Library` and then save the document as bytes. Load the saved document bytes using the [SfPdfViewer.memory()](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.memory.html). The following code example explains the same.

2022-04-22 13:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/500/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 13:27 UTC, dillibabu1802 approved these changes
Approved

2022-04-22 13:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/console)**

2022-04-22 13:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6424-SfPdfViewer](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/flutter-docs/501/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-04-22 13:34 UTC, merged