FLUT-6666 - [Bug] Resolved incorrect code snippet of export to pdf user guide documentation in flutter charts
syncfusion-content/flutter-docs pull request #427
Opened 2022-10-28 04:53 UTC by SriramKiranSenthilkumar

**Description:**

-Resolved the incorrect code snippet provided in the export to pdf user guide documentation section in the cartesian and circular charts.

2022-10-28 04:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/console)**

2022-10-28 04:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-08 08:59 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins-ci.syncfusion.com:8443/job/Content/job/flutter-docs/690/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-11-08 08:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/console)**

2022-11-08 09:00 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/console)**

2022-11-08 09:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/690/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-08 09:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins-ci.syncfusion.com/job/Content/job/flutter-docs/691/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-21 04:41 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/console)**

2022-11-21 04:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/console)**

2022-11-21 04:52 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/685/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-23 10:04 UTC, LavanyaGowtham2021 approved these changes
Changes are fine.

2022-11-23 10:16 UTC, LavanyaGowtham2021 commented
@SriramKiranSenthilkumar Add gif instead of image for exporting ug.

2022-11-28 03:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/console)**

2022-11-28 03:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/686/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-28 03:59 UTC, SriramKiranSenthilkumar commented
> @SriramKiranSenthilkumar Add gif instead of image for exporting ug.Hi @LavanyaGowtham2021,

I have added the gif images for the pdf exporting UG sections. Please check.

-Sriram Kiran

2022-11-28 06:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/console)**

2022-11-28 06:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/687/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-28 09:26 UTC, VijayakumarMariappan requested changes

2022-11-28 09:26 UTC, VijayakumarMariappan commented on Flutter/funnel-chart/export-funnel-chart.md
> +![image_export](images/export-funnel-chart/image_view.gif)
<img width="339" alt="image" src="https://user-images.githubusercontent.com/92971875/204241481-32de24d4-0bef-4975-b5df-858792633f88.png">

Form a git like this

2022-11-29 02:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/console)**

2022-11-29 02:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/688/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-06 10:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/console)**

2022-12-06 10:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [flut-6833-hfx-chartpdf-export-ug](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/689/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-06 13:58 UTC, LavanyaGowtham2021 approved these changes
Changes are fine.

2022-12-07 12:25 UTC, VijayakumarMariappan approved these changes
Changes are fine

2022-12-07 13:19 UTC, merged