FLUT-7009-NamedRangeXlsIO-Dev
syncfusion-content/flutter-docs pull request #446
Opened 2022-12-08 06:34 UTC by KonduruKeerthi

Hi @Mohan2401 ,

Kindly review and merge the changes.

Regards,
Keerthi.

2022-12-08 06:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-7009-NamedRangeXlsIO-Dev](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/691/console)**

2022-12-08 12:10 UTC, Mohan2401 requested changes

2022-12-09 07:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-7009-NamedRangeXlsIO-Dev](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/console)**

2022-12-09 07:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-7009-NamedRangeXlsIO-Dev](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/696/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-09 08:34 UTC, KonduruKeerthi commented on Flutter/xlsio/working-with-excel-worksheet.md
> +//Set formula in the cell.
Made changes as suggested

2022-12-09 08:35 UTC, KonduruKeerthi commented on Flutter/xlsio/working-with-excel-worksheet.md
> +worksheet.getRangeByName('A1:D4').setText('Hello');
Made changes as suggested

2022-12-09 08:35 UTC, KonduruKeerthi commented on Flutter/xlsio/working-with-excel-worksheet.md
> +Cell ranges can be defined by names and used in formulas. This section explains about creating named ranges and accessing them from workbook or worksheet levels.
Made changes as suggested

2022-12-13 13:23 UTC, Mohan2401 approved these changes

2022-12-13 13:23 UTC, merged