FLUT-7137 - [Feature] UG documentation has been added to DataGrid for the filter icon style and popup menu customizing features.
syncfusion-content/flutter-docs pull request #456
Opened 2022-12-15 06:00 UTC by Tamilarasan-Paranthaman

## Description ##

* UG documentation has been added to DataGrid for the `filter icon style` and `popup menu customizing` features.

2022-12-15 06:01 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/704/console)**

2022-12-16 11:17 UTC, NeelakandanKannan requested changes
Get back to me with the changes.

2022-12-19 04:36 UTC, Tamilarasan-Paranthaman commented on Flutter/datagrid/filtering.md
> +### Filter Mode
Modified

2022-12-19 04:36 UTC, Tamilarasan-Paranthaman commented on Flutter/datagrid/filtering.md
> +## Customizing the Filter Popup Menu Options
Modified

2022-12-19 04:37 UTC, Tamilarasan-Paranthaman commented on Flutter/datagrid/filtering.md
> +The Filter popup mode for the column can be set by using the `FilterPopupMenuOptions.filterMode` in `GridColumn.filterPopupMenuOptions` property.
Modified

2022-12-19 04:38 UTC, Tamilarasan-Paranthaman commented on Flutter/datagrid/filtering.md
> +### Hiding column name
I have changed

2022-12-19 04:40 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/console)**

2022-12-19 04:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/console)**

2022-12-19 04:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/706/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-22 06:19 UTC, NeelakandanKannan requested changes
Get back to me with the changes.

2022-12-22 06:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/console)**

2022-12-22 06:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/708/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-22 07:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/console)**

2022-12-22 07:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/709/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-22 07:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/console)**

2022-12-22 07:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-6235-datagrid-cell-style](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/flutter-docs/710/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-22 07:56 UTC, NeelakandanKannan approved these changes
The changes are fine.

2022-12-22 07:56 UTC, merged