FLUT-879690 - [Others] Added user guidelines for roc and wma indicators
syncfusion-content/flutter-docs pull request #863
Opened 2024-05-28 04:27 UTC by natrayansf

## Description ##

Added user guidelines for ROC and WMA indicators

2024-05-28 04:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/console)**

2024-05-28 04:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/console)**

2024-05-28 04:47 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/)<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [84](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/109/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-28 06:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/console)**

2024-05-28 06:42 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/)<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [3](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/110/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-28 07:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/console)**

2024-05-28 07:25 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/flutter-docs/111/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-05-28 09:03 UTC, LavanyaGowtham2021 requested changes

2024-05-28 09:03 UTC, LavanyaGowtham2021 commented on Flutter/cartesian-charts/technical-indicators.md
> +*	[`Weighted moving average indicator`]() (SMA) - can be rendered with five value mappers ([`xValueMapper`](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TechnicalIndicator/xV
WMA

2024-05-28 09:15 UTC, natrayansf commented on Flutter/cartesian-charts/technical-indicators.md
> +                name: 'HiloOpenClose',
Added mapper codes

2024-05-28 09:15 UTC, natrayansf commented on Flutter/cartesian-charts/technical-indicators.md
> +*	[`Weighted moving average indicator`]() (SMA) - can be rendered with five value mappers ([`xValueMapper`](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TechnicalIndicator/xV
Modified to WMA from SMA.

2024-06-03 07:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [FLUT-879690-New-indicators-ug-dev](https://ci.syncfusion.com/job/Content/job/flutter-docs/117/console)**

2024-06-03 12:25 UTC, LavanyaGowtham2021 approved these changes
Fine

2024-06-03 12:25 UTC, merged